__METADATA__
{
  "v3Meta": {
    "objectGuid": "a2c683e5-28a7-44ba-8b63-997885e3a467",
    "objectTypeGuid": "6f9dac99-8de1-4efc-8465-68ac443b7d08",
    "embeddedObjectTypeGuids": [
      "a9ed5b7e-75c5-4651-af16-d2c27e98cb94",
      "3b83b776-fb25-43b8-99f2-3c507c9143fc"
    ],
    "properties": {},
    "subObjects": {}
  }
}
__DECLARATION__
PROGRAM MyCobot
VAR
	fb_Cobot : LCC.FB_CobotController;
END_VAR
__IMPLEMENTATION__
fb_Cobot(
	i_xEnable:= , 
	i_xErrorQuit:= , 
	q_xActive=> , 
	q_xReady=> , 
	q_xError=> , 
	q_etResult=> , 
	q_sResultMsg=> );
